# Generated by Django 6.0.1 on 2026-01-11 07:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Statuses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(help_text='Phone number must be unique', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (min. 8 characters, digits, spaces, +, -, (, ) allowed)', regex='^[\\+\\d][\\d\\s\\-\\(\\)]{7,}$')])),
                ('email', models.EmailField(help_text='Email address must be unique', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('city', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='contacts.contactstatus')),
            ],
            options={
                'ordering': ['-date_added'],
                'indexes': [models.Index(fields=['last_name'], name='contacts_co_last_na_12cfae_idx'), models.Index(fields=['date_added'], name='contacts_co_date_ad_d53fe9_idx'), models.Index(fields=['email'], name='contacts_co_email_25f973_idx'), models.Index(fields=['phone_number'], name='contacts_co_phone_n_6d0af4_idx')],
            },
        ),
    ]
