# Generated by Django 6.0.1 on 2026-01-11 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, spaces, hyphens, and apostrophes', regex="^[a-zA-ZąćęłńóśźżĄĆĘŁŃÓŚŹŻ\\s\\-']+$")]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, spaces, hyphens, and apostrophes', regex="^[a-zA-ZąćęłńóśźżĄĆĘŁŃÓŚŹŻ\\s\\-']+$")]),
        ),
    ]
